# Generated by Django 5.2 on 2025-05-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number must start with 63 followed by 10 digits (e.g., 639123456789)', max_length=20, null=True, unique=True),
        ),
    ]
