# Generated by Django 5.2 on 2025-06-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('features', 'Features'), ('why_train', 'Why Train')], max_length=50, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
