# Generated by Django 5.2 on 2025-06-02 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_legitimateemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legitimateemail',
            name='original_email',
        ),
        migrations.AddField(
            model_name='legitimateemail',
            name='is_real',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legitimateemail',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legitimateemail',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='legitimateemail',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='legitimateemail',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='legitimateemail',
            name='receiver_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='legitimateemail',
            name='sender_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='legitimateemail',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='legitimateemail',
            name='sent_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='legitimateemail',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
