# Generated by Django 5.2 on 2025-06-03 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_legitimateemail_original_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegitimateSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_receiver_number', models.CharField(max_length=20)),
                ('original_message', models.TextField()),
                ('original_sent_at', models.DateTimeField(blank=True, null=True)),
                ('original_sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_original_real', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
