# Generated by Django 5.2 on 2025-06-04 11:33

import django.db.models.deletion
from django.db import migrations, models

def migrate_lessonprogress_to_fk(apps, schema_editor):
    LessonProgress = apps.get_model('authentication', 'LessonProgress')
    AdminLesson = apps.get_model('authentication', 'AdminLesson')
    for lp in LessonProgress.objects.all():
        # If the old field was a string, try to match by title
        if isinstance(lp.lesson, str):
            lesson_obj = AdminLesson.objects.filter(title__iexact=lp.lesson.replace('_', ' ')).first()
            if lesson_obj:
                lp.lesson = lesson_obj
                lp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_adminlesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.adminlesson'),
        ),
        migrations.RunPython(migrate_lessonprogress_to_fk, reverse_code=migrations.RunPython.noop),
    ]
