# Generated by Django 5.2 on 2025-06-04 11:35

import django.db.models.deletion
from django.db import migrations, models

def migrate_lesson_str_to_fk(apps, schema_editor):
    LessonProgress = apps.get_model('authentication', 'LessonProgress')
    AdminLesson = apps.get_model('authentication', 'AdminLesson')
    for lp in LessonProgress.objects.all():
        if lp.lesson:
            lesson_obj = AdminLesson.objects.filter(title__iexact=lp.lesson.replace('_', ' ')).first()
            if lesson_obj:
                lp.lesson_fk = lesson_obj
                lp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_lessonprogress_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson_fk',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.adminlesson'),
        ),
        migrations.RunPython(migrate_lesson_str_to_fk, reverse_code=migrations.RunPython.noop),
    ]
