# Generated by Django 5.2 on 2025-06-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_lessonprogress_lesson_fk_alter_lessonprogress_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='lesson_fk',
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.CharField(max_length=100),
        ),
    ]
