# Generated by Django 5.2 on 2025-06-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_delete_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
